#!/usr/bin/env python3
import sys
import socket
from adf import *
from canbus import CANInterface, CANoverIP

bus = sys.argv[1]
addr = sys.argv[2]
try:
    port = int(sys.argv[3])
except:
    port = 1939
try:
    node = int(sys.argv[4])
except:
    node = 0

print(node, bus, addr, port)

f = Framework()

f.start_plugin(CANInterface, name='can', device=bus)
f.start_plugin(CANoverIP, name='ip', node=node,
               addr=addr, listen=addr, port=port)
f.link_plugin('can', 'ip')

f.join()
